name: ocp_charge_user_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Your existing deps
  gif: ^2.2.0
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0
  http: ^1.1.0

  # Firebase (aligned versions)
  firebase_core: ^2.27.2
  firebase_auth: ^4.17.8
  firebase_database: ^10.5.1

  flutter_launcher_icons: ^0.13.1




  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/OCP_logo.png
  - assets/videos/OCP_video.gif


flutter_icons:
  android: true
  ios: true
  image_path: "assets/OCP_logo.png"
